name: Release

on:
  release:
    types: [ created ]

jobs:
  build_amd64:
    name: Build AMD64 Binaries
    runs-on: ubuntu-latest

    steps:
    - name: Check Permissions
      run: sudo chown -R $USER:$USER /home/$USER/actions-runner/_work/CyberRadio || true

    - uses: actions/checkout@v2

    - name: Build Compiler
      run: make compiler

    - name: Build Installer
      run: make installer

    - name: Build CyberRadio
      run: make build

    - name: Build Release
      run: make release

    - name: Upload Debian Release
      id: upload-debian-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/CyberRadio.deb
        asset_name: CyberRadio.amd64.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload Arch Release
      id: upload-arch-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/CyberRadio.pkg.tar.xz
        asset_name: CyberRadio.amd64.pkg.tar.xz
        asset_content_type: application/x-tar

    - name: Upload Fedora Release
      id: upload-fedora-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/CyberRadio.rpm
        asset_name: CyberRadio.amd64.rpm
        asset_content_type: application/zip

  build_arm64v8:
    name: Build ARM64/V8 Binaries
    runs-on: [ self-hosted, linux, ARM64 ]

    steps:
    - name: Check Permissions
      run: sudo chown -R $USER:$USER /home/$USER/actions-runner/_work/CyberRadio || true

    - uses: actions/checkout@v2

    - name: Build Compiler
      run: make compiler

    - name: Build Installer
      run: make installer

    - name: Build CyberRadio
      run: make build

    - name: Build Release
      run: make release

    - name: Upload Debian Release
      id: upload-debian-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/CyberRadio.deb
        asset_name: CyberRadio.arm64v8.deb
        asset_content_type: application/vnd.debian.binary-package
